### ISSUE TITLE
Random segfault

### ISSUE THREAD

**Issue by NicolasFloquet** [smatcher/S5old#1]
-Le programme plante au bout d'un temps relativement aléatoire

-parfois l'interface graphique apparait et en faisant tourner la caméra ça fini par planter.

-a plusieurs reprise, j'ai eu le message "terminate called after throwing an instance of 'std::bad_alloc' what(): std::bad_alloc"

-Quand l'interface graphique apparait, la liste de noeuds à droite est vide

**Comment by smatcher** [comment]
En effet, ca me le fait sur mon fixe.
Je vérifie sur le netbook quand je peux.
Il faudrait comparer nos versions de g++ et différentes libs.

**Comment by smatcher** [comment]
Bon, il faut penser à faire très très attention quand on mélange pointeurs, templates et héritage multiple.
Normalement maintenant ca marche (j'ai testé sous 2 configurations).
