### ISSUE TITLE
DebugTools

### ISSUE THREAD

**Issue by smatcher** [smatcher/S5old#14]
Isoler le code de debug du code et les widget de debug du code fonctionnel
definir -D_DEBUG dans la ligne de compilation debug

**Comment by NicolasFloquet** [comment]
Pour vérifier j'ai testé ça:

```
void test()
{
#ifdef _DEBUG
printf("Debug\n");
#else
printf("Release\n");
#endif
}
int main(int argc, char** arv)
{
test();
return 0;
}
```

floquetn@XXX[~]$ gcc -o test test.c
floquetn@XXX[~]$ ./test
Release
floquetn@XXX[~]$ gcc -D_DEBUG -o test test.c
floquetn@XXX[~]$ ./test
Debug

Donc ça marche bien. Par contre, j'ai entendu que Qmake par exemple définissait automatiquement la macro "NDEBUG", à vérifier

**Comment by smatcher** [comment]
En debug la macro QT_DEBUG est définie, on est parait t'il pas censés l'utiliser ... actuellement c'est elle que j'utilise dans le systeme de log.
Il faudrait eventuellement definir notre propre macro.

De même, pour les outils de debug il faudrait se baser sur une autre macro, on doit pouvoir compiler une version debug sans debug tool et une version release avec debugtool, c'est avant tout des outils de middle-user (artiste, moddeur ...)

**Comment by smatcher** [comment]
On utilise les macros _DEBUG et WITH_TOOLS
respectivement déclarées sur les configurations s5debug et tools.
