### ISSUE TITLE
Système de log

### ISSUE THREAD

**Issue by smatcher** [smatcher/S5old#15]
Il faudrait un systeme de log multi niveau

les niveaux sont :
log (affiché même en release, avec differents degrés de gravité )
debug (affiché seulement en debug, avec différents degrées de gravité)

les degrés sont :
- info : information utile sur le déroulement de l'application, initialisation, statistiques sur la frame courante ...
- warning : comportement inhabituel mais récupérable.
- error : comportement inhabituel grave voir fatal

il est possible de spécifier au runtime  les degrés de gravité affichés.
Chaque message précise également un sujet et il est possible de filtrer au runtime pour afficher seulement certains sujets.

Le log contiendra en plus de ces informations le nom de fichier ainsi que le numero de ligne.

**Comment by NicolasFloquet** [comment]
Tant qu'a faire, on pourrait ajouter à ça un comportement.
Donc on choisi au runtime de l'afficher ou non, et par exemple au peut demander au programme de s'arreter au moindre warning, ou en cas d'erreur, ou jamais.
T'en pense quoi?

**Comment by smatcher** [comment]
Arretter le programme revient à faire un assert.
Je crois pas que ca aille dans le log, en revanche on pourrait avoir nos propres assert qui testent une condition et affichent un log avant de quitter si la condition n'est pas respectée. Ces assert pouvant être desactivés en release.

Disons que le seul interet que je vois à couper le programme au moindre warning c'est pour du debuging post mortem, vu la merde que c'est, autant lancer en debug avec un breakpoint dans le systeme de log.

**Comment by smatcher** [comment]
C'est fait, je laisse l'issue ouverte pour commentaires et remarques.
(PS : je me base sur la macro QT_DEBUG, il faudra éventuellement revoir ca)
