### ISSUE TITLE
Primitives

### ISSUE THREAD

**Issue by smatcher** [smatcher/S5old#16]
Développer des primitives :
Plan
Cube
Sphere
...

**Comment by NicolasFloquet** [comment]
Juste pour avoir plus de précisions, ça servirait à quoi?

**Comment by smatcher** [comment]
Outre pour le prototypage pur et dur.
Ca peut servir pour faire des sprites ou pour des objets qui ont une forme basique de ce genre (ballon, caisse, projectiles ...)
Ajouter un fichier pour un modele aussi basique c'est dommage, surtout qu'on pourrait envisager une factory de primitives à laquelle on pourrait demander des meshs aux dimensions, nombre de vertex particulier.
