### ISSUE TITLE
Tentative dessin sur un contexte openGL détruit lorsque la fenêtre est fermée.

### ISSUE THREAD

**Issue by smatcher** [smatcher/S5old#4]
Lorsqu'on ferme l'application, Qt détruit le contexte openGL alors que le thread de jeu l'utilise encore. Il faudrait trouver comment synchroniser les thread pour laisser le temps au thread de jeu de finir proprement avant de détruire le contexte.

Node : penser à laisser un timeout à la synchonisation pour le cas ou le thread de jeu tombe dans une boucle infini, il faut pouvoir fermer l'application dans ce genre de cas.

**Comment by NicolasFloquet** [comment]
On pourrait pas juste faire en sorte que le thread de la fenetre envoie son signal QThread::terminated() quand on le ferme, et que ce signal soit bindé au QThread::terminate() du thread de jeu?

**Comment by smatcher** [comment]
Fixed :
En fait c'etait pas ca, c'etait le thread qui gardait le contexte quand il devait être détruit.
J'ai ajouté un appel à doneCurrent en sortie d'initialisation et de rendu.
